### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FrankGarcia97** [kruizer23/hotframefx#17]
Is anyone aware if the app is still being supported? I see many requests for cool features, and it seems like the author agrees to implement them, but nothing progress for a long time.

**Comment by kruizer23** [comment]
Yep, it's still supported. Just keep in mind that this is a hobby project and I only work on it if time permits and when I feel like it.

The online user manual contains [a section](https://kruizer23.github.io/hotframefx/contributing/) on how you can setup the development environment yourself and contribute code. If there's a feature you really want, feel free to implement it and I'll merge your changes.

**Comment by FrankGarcia97** [comment]
> Yep, it's still supported. Just keep in mind that this is a hobby project and I only work on it if time permits and when I feel like it.
> 
> The online user manual contains [a section](https://kruizer23.github.io/hotframefx/contributing/) on how you can setup the development environment yourself and contribute code. If there's a feature you really want, feel free to implement it and I'll merge your changes.

I'm sorry if I offended you in any way, that wasn't my intention. I was just genuinely curious about the project's development. I'm not a programmer, so I can't help in that regard, unfortunately. I started using this application a few months ago, and among all the ones I've tried, this one feels the best. The only thing I started missing over time is the ability to set individual sensitivities for each corner. When I checked the "issues" section, I saw that this issue had already been raised, so I decided to wait. Recently, I bought an additional monitor and noticed that the application doesn't support multiple monitors. Again, when I checked the "issues" section, I saw that this issue had also been raised. That's when I decided to check the app's publication date and saw that the last of the two versions was released back in March, which is quite a long time, as most apps, from my observation, release updates every few months, usually with minor or cosmetic changes, but it shows that the project is still alive. That's why I decided to ask the community if this project is still being supported. I understand that some feature requests may be complex and require additional research, like multi-monitor support, but things like individual sensitivity for each corner or the ability to hide the tray icon don't seem too complicated. Once again, I apologize. I'll just wait for updates, knowing that they will eventually come.

**Comment by kruizer23** [comment]
Thank you for your response and no worries, I wasn't offended in any way. I just wanted to clarify why it takes a bit longer for new features to be implemented.

I initially developed HotFrameFx for my own usage and decided to make it available for others as well. It already does everything I personally need and therefore implementing new features gets a bit of a lower priority. I can definitely understand why others would like to see their requested features implemented. They are all good ideas. 

For this reason I added a section to the user manual describing how to setup the development environment, hoping that this lowers the entry level for others to contribute to the project. Additionally, the winter time is coming up and that's where I typically do more coding.

Take care!

**Comment by FrankGarcia97** [comment]
@kruizer23 🥲
